"""Workout node for genuinely-bankrupt borrowers.

Handles 実質破綻先 (De facto Bankrupt) and 破綻先 (Bankrupt) borrowers that
have been routed here by ``route_after_classification`` via the
``requires_workout`` property on :class:`~app.shared.models.classification.FsaClass`.

This node is DETERMINISTIC and TERMINAL: it records a legal/liquidation handoff
into an additive state field and ends the graph. No LLM is involved.

The handoff message is a structured, auditable record of the routing decision
so the bank's workout team can pick up the case. It is NOT generated by an LLM.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from app.backend.state import SaiseiState
from app.shared.logging import get_logger
from app.shared.models.loan import (
    LoanEvent,
    current_status,
    outstanding_principal_for_state,
    proposed_transition_for,
    provision_amount,
)
from app.shared.models.money import format_jpy

__all__ = ["workout_node"]

_log = get_logger(__name__)


def _persist_loan_events(state: SaiseiState, events: list[dict[str, Any]]) -> None:
    """Best-effort durable append of new loan events to the loan store.

    Mirrors the audit ledger's ``record_event`` posture: a strict side-record
    that NEVER affects the node's return, a gate, a route, or a figure, and is
    NEVER fatal. The events are already in the LangGraph checkpointer state
    (via the node's ``loan_events`` return); this additionally persists them to
    the dedicated, append-only, tenant-scoped loan ledger so a facility's
    lifecycle is durable in its own store.

    Offline (no ``SAISEI_LOAN_DSN``) the factory returns ``NullLoanStore`` and
    this is a no-op, keeping the system byte-stable. A no-op also occurs when no
    loan is attached or there are no new events.

    Args:
        state: Current graph state (source of ``loan_id`` + tenant scope).
        events: The newly recorded LoanEvent dicts the node is appending.
    """
    if not events or not state.loan_id:
        return
    try:
        from app.backend.portfolio.loan_store_postgres import get_loan_store
        from app.shared.settings import get_settings

        settings = get_settings()
        store = get_loan_store(settings.loan_dsn)
        tenant_id = settings.loan_tenant_default
        for raw in events:
            store.append(tenant_id, state.loan_id, LoanEvent.model_validate(raw))
        _log.info(
            "workout.loan_persisted",
            loan_id=state.loan_id,
            count=len(events),
        )
    except Exception as exc:  # noqa: BLE001 - persistence is best-effort, never fatal
        _log.warning("workout.loan_persist_failed", error=str(exc), loan_id=state.loan_id)


def _now_utc() -> dt.datetime:
    """Return the current UTC timestamp (isolated for test patchability)."""
    return dt.datetime.now(dt.UTC)


def _outstanding_principal(state: SaiseiState) -> int:
    """Return the facility's TRUE outstanding principal (残高), or 0.

    Delegates to the shared :func:`outstanding_principal_for_state` seam: the
    lender-stakes sum (original principal) minus the cumulative repayments on the
    loan log. With no repayments this equals the old proxy exactly; once a
    facility amortizes it is the real declining balance, so the workout-team
    provision (貸倒引当金) reserves against the truthful exposure. Returns 0 when no
    stake data is present so the provision line is omitted rather than guessed.
    """
    return outstanding_principal_for_state(state)


def _loan_workout_event(state: SaiseiState) -> list[dict[str, Any]]:
    """Record the loan-lifecycle transition implied by a workout handoff.

    This is the realisation point of the loan-lifecycle spine on the WORKOUT
    path: when a loan is attached to the run and its current FSA classification
    implies a 管理回収 (WORKOUT) transition that is legal from the loan's current
    status, the deterministic workout routing records that transition as a
    single immutable :class:`~app.shared.models.loan.LoanEvent` appended to the
    append-only log.

    Authority note: unlike the turnaround path -- where the banker's HITL
    approval is the decider -- a workout handoff is the DETERMINISTIC terminal
    decision mandated by the classifier (``fsa_classification.requires_workout``).
    There is no banker negotiation on this path by design, so the event is
    authored by ``"system"`` (the classifier), exactly as the intake bootstrap
    authors its monitoring events. No LLM is involved, and the event feeds no
    gate, route, or figure.

    Returns ``[]`` (append-only reducer no-op) when no loan is attached, no FSA
    classification is set, the classification implies no transition, or the
    implied transition is not legal from the current status (e.g. an already
    terminal facility).

    Args:
        state: Current graph state at workout time.

    Returns:
        A list with zero or one ``LoanEvent`` dict to append.
    """
    if not state.loan_id or state.fsa_classification is None:
        return []
    if not state.loan_events:
        return []  # no prior log to transition from

    try:
        current = current_status([LoanEvent.model_validate(e) for e in state.loan_events])
    except Exception as exc:  # noqa: BLE001 - never break the terminal handoff
        _log.warning("workout.loan_status_failed", error=str(exc), loan_id=state.loan_id)
        return []

    target = proposed_transition_for(state.fsa_classification, current)
    if target is None:
        return []

    event = LoanEvent(
        status=target,
        at=_now_utc(),
        actor="system",
        note=(
            f"FSA {state.fsa_classification.value} workout handoff: "
            f"{current.value} -> {target.value} (deterministic routing)"
        ),
    )
    _log.info(
        "workout.loan_transition",
        loan_id=state.loan_id,
        current=current.value,
        target=target.value,
    )
    return [event.model_dump(mode="json")]


def workout_node(state: SaiseiState) -> dict[str, Any]:
    """Record a legal/liquidation handoff for a bankrupt borrower.

    This node is reached only for 実質破綻先 and 破綻先 borrowers (those whose
    ``fsa_classification.requires_workout`` is True). It records a structured
    handoff into ``workout_handoff`` and logs the event for the workout team.

    The handoff is deterministic: it records the classification, EWS score,
    insolvency signals, net worth, working-capital gap, and the loan-loss
    provision (貸倒引当金) so the workout team has a complete audit trail. No
    LLM is involved.

    Args:
        state: Current graph state.

    Returns:
        Partial state update with ``workout_handoff`` set to the handoff record
        and any loan-lifecycle WORKOUT transition appended to ``loan_events``.
    """
    classification = state.fsa_classification
    kanji = classification.kanji if classification else "不明"
    english = classification.english if classification else "Unknown"

    if state.net_worth is not None:
        net_worth_line = f"純資産 (Net Worth): {format_jpy(int(state.net_worth))}"
    else:
        net_worth_line = "純資産: 未評価"

    if state.working_capital_gap is not None:
        gap_line = (
            f"資金繰りギャップ (Working Capital Gap): {format_jpy(int(state.working_capital_gap))}"
        )
    else:
        gap_line = "資金繰りギャップ: 未評価"

    # Loan-loss provision (貸倒引当金): deterministic from outstanding principal
    # (sum of lender_stakes) and the FSA class. For a bankrupt borrower the
    # reserve ratio is 1.0, so the provision equals the full outstanding
    # balance -- the figure the workout team most needs. Omitted when no
    # outstanding balance is known (no stake data), rather than guessed.
    outstanding = _outstanding_principal(state)
    if classification is not None and outstanding > 0:
        provision = provision_amount(
            outstanding,
            classification,
            special_attention=bool(state.special_attention),
        )
        provision_line = (
            "貸倒引当金 (Loan-loss Provision): "
            f"{format_jpy(provision)} "
            f"(引当対象残高 {format_jpy(outstanding)})"
        )
    else:
        provision_line = "貸倒引当金: 未評価 (残高未確認)"

    handoff_lines = [
        "=== WORKOUT HANDOFF / 法的整理・清算引継ぎ ===",
        f"債務者区分 (FSA Class): {kanji} ({english})",
        f"EWSスコア: {state.ews_score}",
        net_worth_line,
        f"債務超過フラグ (is_insolvent): {state.is_insolvent}",
        gap_line,
        provision_line,
        "---",
        "本件は法的整理・清算手続きの対象です。ワークアウト担当部署へ引き継いでください。",
        "(This borrower requires legal restructuring or liquidation "
        "proceedings. Hand off to the workout / special assets team.)",
    ]
    handoff = "\n".join(handoff_lines)

    _log.info(
        "workout.handoff",
        fsa_classification=classification.value if classification else None,
        kanji=kanji,
        ews_score=state.ews_score,
        net_worth=state.net_worth,
        is_insolvent=state.is_insolvent,
        outstanding_principal=outstanding,
    )

    loan_events = _loan_workout_event(state)
    # Durable side-record: persist the WORKOUT transition to the dedicated
    # append-only loan ledger (offline no-op without SAISEI_LOAN_DSN). The events
    # are already on the return below; this never affects the return, a gate, a
    # route, or a figure, and is never fatal.
    _persist_loan_events(state, loan_events)

    return {
        "workout_handoff": handoff,
        # Loan-lifecycle bridge: record the FSA-implied 管理回収 (WORKOUT)
        # transition on the deterministic terminal path. Append-only no-op when
        # no loan is attached / the transition is not legal. Never feeds a gate,
        # route, or figure.
        "loan_events": loan_events,
    }
